accordproject/cicero-vscode-extension

README.md
Signed-off-by: Peter Hunn <peter@peterhunn.com>
=> docs(README): add trademark policy - I6

server/package-lock.json, server/package.json
- Ran locally and found no bugs
- Possibly just did not come across an existing bug
- Need to publish a release for pushing this through to VSCode marketplace
=> chore(server): update cicero 0.13.4 and ergo 0.9.4

client/package.json, client/server/package.json, server/package.json
Fix to sync this version to Cicero version
=> chore(package): adjust version to coincide with cicero

README.md
=> docs(README): fix typo - I15

README.md
Signed-off-by: Aayush Bisen <aayush23101998@outlook.com>
Centered Accord Project Logo
- Centered logo of Accord Project in README
- None
- https://github.com/accordproject/techdocs/issues/79
=> docs(README): center Accord Project logo

README.md
Related to accordproject/techdocs#80
=> feat(readme): add ecosystem table

README.md
Signed-off-by: Aayush Bisen <aayush23101998@outlook.com>
Updated the Slack badge, fixed typos in README.
- Updates the Slack badge in README.
- Fixes minor typos in README.
- None
- https://github.com/accordproject/techdocs/issues/78
=> docs(README): update slack badge, fix typos

client/package-lock.json, client/package.json, client/server/package-lock.json, client/server/package.json, server/package-lock.json, server/package.json
=> chore(dep) Switch to Cicero 0.20.1

client/package-lock.json, client/package.json, client/server/package-lock.json, client/server/package.json, server/package-lock.json, server/package.json
=> chore(rel) Update to Ergo and Cicero 0.20.2

client/package-lock.json, client/package.json, client/server/package-lock.json, client/server/package.json, server/package-lock.json, server/package.json
=> chore(dep) Upgrade for Cicero 0.20.5

client/package.json, client/server/package-lock.json, client/server/package.json, server/package-lock.json, server/package.json
=> chore(dep) Upgrade for Cicero 0.20.6

client/package-lock.json, client/package.json, client/server/package-lock.json, client/server/package.json, server/package-lock.json, server/package.json
=> chore(dep) Upgrade to Cicero 0.20.7

client/package-lock.json, client/package.json, client/server/package-lock.json, client/server/package.json, server/package-lock.json, server/package.json
=> chore(dep) Upgrade to Cicero 0.20.9

client/package.json, client/server/package-lock.json, client/snippets/concerto.json
<OVERALL SUMMARY OF PULL REQUEST>
This Pr provide snippets for Concerto Language.  This will be the new feature for the Plugin.
=> Adding Snippets for Concerto Language

README.md
<OVERALL SUMMARY OF PULL REQUEST>
This pr generally adds documentation for the generation of snippets for the concerto language.
=> Updating Docs Regarding Snippets

client/package-lock.json, client/package.json, client/server/package-lock.json, client/server/package.json, server/package-lock.json, server/package.json
=> chore(release) Upgrade to Cicero 0.20.10

client/package-lock.json, client/package.json, client/server/package-lock.json, client/server/package.json, server/package-lock.json, server/package.json
=> fix(build) corrects version in server package, update to 0.21.1

CHANGELOG.md, client/package-lock.json, client/package.json, package-lock.json, package.json, server/package-lock.json, server/package.json
=> chore(dep) Upgrade to Cicero 0.21.7

CHANGELOG.md, client/package-lock.json, client/package.json, package-lock.json, package.json, server/package-lock.json, server/package.json
=> chore(dep) Upgrade for Cicero 0.21.8

CHANGELOG.md, client/package-lock.json, client/package.json, client/src/commandHandlers.ts, package-lock.json, package.json, server/package-lock.json, server/package.json, server/src/server.ts
Signed-off-by: Dan Selman <danscode@selman.org>
Updates the VSCode extension to use the latest version of VSCode and Cicero v0.22.
- Minor changes to the usage of the ModelManager
- Minor changes to the usage of the LogicManager (es6 vs cicero)
- Update VSCode
- <ONE>
- <TWO>
- Issue #<NUMBER>
- Pull Request #<NUMBER>
=> feat(cicero) : update to cicero v0.22

README.md
Signed-off-by: Ayman161803 <mohammedaymannawaz@gmail.com>
- Change the invite links from slack to discord
- Files changed: README.md
- Issue accordproject/cicero-vscode-extension#121
=> doc(README.md): Update discord invite links

README.md, babel.config.json, client/package-lock.json, client/package.json, client/src/extension.ts, client/src/utils.ts, client/src/webClientMain.ts, client/src/webCommandHandlers.ts, package-lock.json, package.json, webpack.config.js
Signed-off-by: Ayman161803 <mohammedaymannawaz@gmail.com>
- Increment concerto tools version
- Expose codegen and draft from context menu
https://user-images.githubusercontent.com/76606666/186146220-08ed3313-2d3b-4727-82e9-da29e9075115.mov
https://user-images.githubusercontent.com/76606666/186147390-6298ccb8-0101-4617-b9c2-5ac62da88159.mov
=> Add codegen, draft feature to context menu and updated docs
